[package]
name = "config"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
dirs = "6.0.0"
toml = "0.8.23"
tracing = {workspace = true}
