[package]
name = "git_changes"
version = "0.0.0"
edition = {workspace = true}
publish = false

[lib]

[dependencies]
git2 = {workspace = true}
tracing = {workspace = true}
chrono = {workspace = true}
